Frontend
zwospiel/Calculator.js pull request #27
Opened 2022-11-28 17:13 UTC by zwospiel

Import is failing, did you forget to push your frontend branch? I manually added type="module", but I can't import Expression.js correctly.

2022-11-28 17:29 UTC, c-auri commented
Yes I forgot. I pushed my changes to origin/module instead, you should be able to rebase onto that without too much trouble.

To import the `Expression` class you will need the following statement: `import { Expression } from "./Expression.js"`. If you have trouble with the multiplication, commit a working state for `+` first and only then try to tackle `×`. And please don't edit the markup, you can get everything done inside `app.js` as it is.

2022-11-29 18:23 UTC, c-auri requested changes

2022-11-29 18:23 UTC, c-auri commented on src/js/Expression.js
> -
Sei mal nicht so unspendabel.

2022-11-29 20:10 UTC, zwospiel commented on src/js/Expression.js
> -
Done.

2022-11-30 09:07 UTC, c-auri approved these changes

2022-11-30 09:07 UTC, merged