Expression
zwospiel/Calculator.js pull request #28
Opened 2022-11-29 12:00 UTC by zwospiel

Only tests.

2022-11-30 18:28 UTC, zwospiel commented
One test is failing, because the test for InvalidInput Error occurs before the UnknownOperator Error, not sure what to do with that. All other tests are succeeding.

2022-12-18 17:43 UTC, c-auri requested changes
Let's talk about the minor issues in the next meeting.

2022-12-18 17:43 UTC, c-auri commented on tests/Expression.test.js
> +        test("for operator at the beginning preceded by whitespaces", () => {
This test cast can be moved down into the "ignores whitespace" group.

2022-12-18 17:43 UTC, c-auri commented on tests/Expression.test.js
> +        test("for operator at the end followed by whitespaces", () => {
This test cast can be moved down into the "ignores whitespace" group.

2022-12-18 17:43 UTC, c-auri commented on src/js/Expression.js
> +                throw new InvalidInput(this.#input)
Did we decide to change something about the `InvalidInput` error in `Operators.apply`? I don't remember exactly.

2022-12-20 19:47 UTC, c-auri approved these changes

2022-12-20 19:47 UTC, merged